# =============================================
# Configuration Email (Gmail SMTP)
# =============================================
# Remplacez par votre email Gmail
email.sender=eyahmad03@gmail.com
# Remplacez par votre "App Password" Gmail (pas votre mot de passe normal)
# Activez : Google Account > Securite > Authentification 2 facteurs > App Passwords
email.password=ccyzgldyaucxtgrm
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.app.name=Psychology App

# =============================================
# Configuration ImgBB (Image Upload)
# =============================================
# Obtenez votre clé API gratuite sur https://api.imgbb.com/
imgbb.api_key=0a09accb8ab3c518c68f0a402e12fc5c


# =============================================
# Configuration Face++ (Reconnaissance Faciale)
# =============================================
# Obtenez vos identifiants sur https://www.faceplusplus.com/
faceplusplus.api_key=WcNhtR7CgcEjyaCA0Lghlf4QsJZS2RJ9
faceplusplus.api_secret=F4toizN_gp1FaUQRchwEqtAxDAZqlD_l
# =============================================
# Configuration Gemini AI
# =============================================
gemini.api.key=AIzaSyCooCKPmgN_U2mgELuCbLJwP1B2tgZ6Fos
grok.api.key=xai-tR0AKRKfyv9RjTyMMf6odp3CEL0r8YMY2drITRlsBzH6SASYp3RmWY8s72X9kYxevHJ0pHNNWSGc6vdk
openai.api.key=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

# =============================================
# Configuration Database
# =============================================
db.url=jdbc:mysql://mysql-215c945b-ademsansa7-4324.j.aivencloud.com:28053/slouma?useSSL=false&serverTimezone=UTC
db.user=avnadmin
db.password=AVNS_HLKPMcODDZfHGeEF1Kl